export const SkillOptions = [
    {key: 'Java', text: 'Java', value: 'Java'},
    {key: 'JavaScript', text: 'JavaScript', value: 'JavaScript'},
    {key: 'Python', text: 'Python', value: 'Python'},
    {key: 'C++', text: 'C++', value: 'C++'},
    {key: 'C#', text: 'C#', value: 'C#'},
    {key: 'PHP', text: 'PHP', value: 'PHP'},
    {key: 'TypeScript', text: 'TypeScript', value: 'TypeScript'},
    {key: 'Ruby', text: 'Ruby', value: 'Ruby'},
    {key: 'Swift', text: 'Swift', value: 'Swift'},
    {key: 'Objective-C', text: 'Objective-C', value: 'Objective-C'},
    {key: 'Kotlin', text: 'Kotlin', value: 'Kotlin'},
    {key: 'Scala', text: 'Scala', value: 'Scala'},
    {key: 'R', text: 'R', value: 'R'},
    {key: 'VBA', text: 'VBA', value: 'VBA'},
    {key: 'Go', text: 'Go', value: 'Go'},
    {key: 'Perl', text: 'Perl', value: 'Perl'},
    {key: 'Assembly', text: 'Assembly', value: 'Assembly'},
    {key: 'MATLAB', text: 'MATLAB', value: 'MATLAB'},
    {key: 'Visual Basic', text: 'Visual Basic', value: 'Visual Basic'},
    {key: 'Rust', text: 'Rust', value: 'Rust'},
    {key: 'Angular', text: 'Angular', value: 'Angular'},
    {key: 'React', text: 'React', value: 'React'},
    {key: 'Vue', text: 'Vue', value: 'Vue'},
    {key: 'Ember', text: 'Ember', value: 'Ember'},
    {key: 'Backbone', text: 'Backbone', value: 'Backbone'},
    {key: 'jQuery', text: 'jQuery', value: 'jQuery'},
    {key: 'Node.js', text: 'Node.js', value: 'Node.js'},
    {key: 'Django', text: 'Django', value: 'Django'},
    {key: 'Flask', text: 'Flask', value: 'Flask'},
    {key: 'Spring', text: 'Spring', value: 'Spring'},
    {key: 'Laravel', text: 'Laravel', value: 'Laravel'},
    {key: 'Express', text: 'Express', value: 'Express'},
    {key: 'Ruby on Rails', text: 'Ruby on Rails', value: 'Ruby on Rails'},
    {key: 'ASP.NET', text: 'ASP.NET', value: 'ASP.NET'},
    {key: 'Cordova', text: 'Cordova', value: 'Cordova'},
    {key: 'Flutter', text: 'Flutter', value: 'Flutter'},
    {key: 'Xamarin', text: 'Xamarin', value: 'Xamarin'},
    {key: 'React Native', text: 'React Native', value: 'React Native'},
    {key: 'Ionic', text: 'Ionic', value: 'Ionic'},
    {key: 'PhoneGap', text: 'PhoneGap', value: 'PhoneGap'},
    {key: 'NativeScript', text: 'NativeScript', value: 'NativeScript'},
]
