export const SkillOptions = [
    {text: 'Java', value: 'Java'},
    {text: 'JavaScript', value: 'JavaScript'},
    {text: 'Python', value: 'Python'},
    {text: 'C++', value: 'C++'},
    {text: 'C#', value: 'C#'},
    {text: 'PHP', value: 'PHP'},
    {text: 'TypeScript', value: 'TypeScript'},
    {text: 'Ruby', value: 'Ruby'},
    {text: 'Swift', value: 'Swift'},
    {text: 'Objective-C', value: 'Objective-C'},
    {text: 'Kotlin', value: 'Kotlin'},
    {text: 'Scala', value: 'Scala'},
    {text: 'R', value: 'R'},
    {text: 'VBA', value: 'VBA'},
    {text: 'Go', value: 'Go'},
    {text: 'Perl', value: 'Perl'},
    {text: 'Assembly', value: 'Assembly'},
    {text: 'MATLAB', value: 'MATLAB'},
    {text: 'Visual Basic', value: 'Visual Basic'},
    {text: 'Rust', value: 'Rust'},
    {text: 'Dart', value: 'Dart'},
    {text: 'Elixir', value: 'Elixir'},
    {text: 'Haskell', value: 'Haskell'},
    {text: 'Julia', value: 'Julia'},
    {text: 'Lua', value: 'Lua'},
    {text: 'Clojure', value: 'Clojure'},
    {text: 'Groovy', value: 'Groovy'},
    {text: 'Delphi/Object Pascal', value: 'Delphi/Object Pascal'},
    {text: 'PowerShell', value: 'PowerShell'},
    {text: 'RPG', value: 'RPG'},
    {text: 'PL/SQL', value: 'PL/SQL'},
    {text: 'Scratch', value: 'Scratch'},
    {text: 'COBOL', value: 'COBOL'},
    {text: 'Ada', value: 'Ada'},
    {text: 'Fortran', value: 'Fortran'},
    {text: 'ABAP', value: 'ABAP'},
    {text: 'Transact-SQL', value: 'Transact-SQL'},
    {text: 'Apex', value: 'Apex'},
    {text: 'Crystal', value: 'Crystal'},
    {text: 'Scheme', value: 'Scheme'},
    {text: 'Visual Basic .NET', value: 'Visual Basic .NET'},
    {text: 'Ladder Logic', value: 'Ladder Logic'},
    {text: 'COBOL', value: 'COBOL'},
    {text: 'Bash', value: 'Bash'},
    {text: 'ActionScript', value: 'ActionScript'},
    {text: 'D', value: 'D'},
    {text: 'F#', value: 'F#'},
    {text: 'Groovy', value: 'Groovy'},
    {text: 'Lisp', value: 'Lisp'},
    {text: 'Prolog', value: 'Prolog'},
    {text: 'ABAP', value: 'ABAP'},
    {text: 'Dart', value: 'Dart'},
    {text: 'Julia', value: 'Julia'},
    {text: 'Lua', value: 'Lua'},
    {text: 'Apex', value: 'Apex'},
    {text: 'Elixir', value: 'Elixir'},
    {text: 'Haskell', value: 'Haskell'},
    {text: 'Kotlin', value: 'Kotlin'},
    {text: 'Rust', value: 'Rust'},
    {text: 'Scala', value: 'Scala'},
    {text: 'Scheme', value: 'Scheme'},
    {text: 'Swift', value: 'Swift'},
    {text: 'VBA', value: 'VBA'},
    {text: 'COBOL', value: 'COBOL'},
    {text: 'ABAP', value: 'ABAP'},
    {text: 'Ladder Logic', value: 'Ladder Logic'},
    {text: 'Scratch', value: 'Scratch'},
    {text: 'RPG', value: 'RPG'},
    {text: 'PL/SQL', value: 'PL/SQL'},
    {text: 'Transact-SQL', value: 'Transact-SQL'},
    {text: 'Apex', value: 'Apex'},
    {text: 'Crystal', value: 'Crystal'},
    {text: 'Scheme', value: 'Scheme'},
    {text: 'Visual Basic .NET', value: 'Visual Basic .NET'},
    {text: 'PowerShell', value: 'PowerShell'},
    
]