networks:
  profesinet:

services:
  profesinet-db:
    container_name: profesiNet-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "8002:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourComplexPassword123!
      - MSSQL_SA_PASSWORD=YourComplexPassword123!
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
    networks:
      - profesinet
  
  profesinet-api:
    container_name: profesiNet-api
    image: profesinet-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - profesinet-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - profesinet