networks:
  mynetwork: null
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profesiNet-api
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - 80:80
  db:
    container_name: profesiNet-db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourComplexPassword123!
      SA_USERNAME: sa
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - mynetwork
    ports:
      - 1433:1433
version: '3.9'
